# Tarea Nº 3 — Inteligencia Artificial

**Estudiante:** Maximiliano Solorza  
**Fecha de entrega:** Domingo 28 de Junio de 2026

In [4]:
# === instalacion librerias necesarias === #
#!pip install numpy pandas matplotlib pgmpy ipywidgets seaborn scikit-learn tensorflow imbalanced-learn tf-keras
%pip install numpy pandas matplotlib pgmpy ipywidgets seaborn scikit-learn tensorflow imbalanced-learn tf-keras
# ======================================== #

Requirement already satisfied: numpy in ./lib/python3.12/site-packages (2.5.0)
Requirement already satisfied: pandas in ./lib/python3.12/site-packages (3.0.4)
Requirement already satisfied: matplotlib in ./lib/python3.12/site-packages (3.11.0)
Requirement already satisfied: pgmpy in ./lib/python3.12/site-packages (1.1.2)
Requirement already satisfied: ipywidgets in ./lib/python3.12/site-packages (8.1.8)
Requirement already satisfied: seaborn in ./lib/python3.12/site-packages (0.13.2)
Requirement already satisfied: scikit-learn in ./lib/python3.12/site-packages (1.9.0)
Collecting tensorflow
  Downloading tensorflow-2.21.0-cp312-cp312-manylinux_2_27_x86_64.whl.metadata (4.4 kB)
Requirement already satisfied: imbalanced-learn in ./lib/python3.12/site-packages (0.14.2)
Collecting tf-keras
  Downloading tf_keras-2.21.0-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in ./lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in ./lib/python3.12/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in ./lib/python3.12/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in ./lib/python3.12/site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in ./lib/python3.12/site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in ./lib/python3.12/site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=9 in ./lib/python3.12/site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in ./lib/python3.12/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: huggingface_hub>=0.23 in ./lib/python3.12/site-packages (from pgmpy) (1.21.0)
Requirement already satisfied: networkx>=3.0 in ./lib/python3.12/site-packages (from pgmpy) (3.6.1)
Requirement already satisfied: scipy>=1.10 in ./lib/python3.12/site-packages (from pgmpy) (1.18.0)
Requirement already satisfied: statsmodels>=0.14.5 in ./lib/python3.12/site-packages (from pgmpy) (0.14.6)
Requirement already satisfied: tqdm>=4.64 in ./lib/python3.12/site-packages (from pgmpy) (4.68.3)
Requirement already satisfied: joblib>=1.2 in ./lib/python3.12/site-packages (from pgmpy) (1.5.3)
Requirement already satisfied: opt_einsum>=3.3 in ./lib/python3.12/site-packages (from pgmpy) (3.4.0)
Requirement already satisfied: scikit-base>=0.12.4 in ./lib/python3.12/site-packages (from pgmpy) (1.0.2)
Requirement already satisfied: comm>=0.1.3 in ./lib/python3.12/site-packages (from ipywidgets) (0.2.3)
Requirement already satisfied: ipython>=6.1.0 in ./lib/python3.12/site-packages (from ipywidgets) (9.15.0)
Requirement already satisfied: traitlets>=4.3.1 in ./lib/python3.12/site-packages (from ipywidgets) (5.15.1)
Requirement already satisfied: widgetsnbextension~=4.0.14 in ./lib/python3.12/site-packages (from ipywidgets) (4.0.15)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in ./lib/python3.12/site-packages (from ipywidgets) (3.0.16)
Requirement already satisfied: narwhals>=2.0.1 in ./lib/python3.12/site-packages (from scikit-learn) (2.22.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in ./lib/python3.12/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: absl-py>=1.0.0 in ./lib/python3.12/site-packages (from tensorflow) (2.4.0)
Requirement already satisfied: astunparse>=1.6.0 in ./lib/python3.12/site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in ./lib/python3.12/site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in ./lib/python3.12/site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in ./lib/python3.12/site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in ./lib/python3.12/site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in ./lib/python3.12/site-packages (from tensorflow) (7.35.1)
Requirement already satisfied: requests<3,>=2.21.0 in ./lib/python3.12/site-packages (from tensorflow) (2.34.2)
Requirement already satisfied: setuptools in ./lib/python3.12/site-packages (from tensorflow) (82.0.1)
Requirement already satisfied: six>=1.12.0 in ./lib/python3.12/site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in ./lib/python3.12/site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in ./lib/python3.12/site-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in ./lib/python3.12/site-packages (from tensorflow) (2.2.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in ./lib/python3.12/site-packages (from tensorflow) (1.81.1)
Requirement already satisfied: keras>=3.12.0 in ./lib/python3.12/site-packages (from tensorflow) (3.15.0)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in ./lib/python3.12/site-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in ./lib/python3.12/site-packages (from tensorflow) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in ./lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in ./lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in ./lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in ./lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow) (2026.6.17)
Requirement already satisfied: sklearn-compat<0.2,>=0.1.6 in ./lib/python3.12/site-packages (from imbalanced-learn) (0.1.6)
Requirement already satisfied: wheel<1.0,>=0.23.0 in ./lib/python3.12/site-packages (from astunparse>=1.6.0->tensorflow) (0.47.0)
Requirement already satisfied: click>=8.4.0 in ./lib/python3.12/site-packages (from huggingface_hub>=0.23->pgmpy) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in ./lib/python3.12/site-packages (from huggingface_hub>=0.23->pgmpy) (3.29.4)
Requirement already satisfied: fsspec>=2023.5.0 in ./lib/python3.12/site-packages (from huggingface_hub>=0.23->pgmpy) (2026.6.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in ./lib/python3.12/site-packages (from huggingface_hub>=0.23->pgmpy) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in ./lib/python3.12/site-packages (from huggingface_hub>=0.23->pgmpy) (0.28.1)
Requirement already satisfied: pyyaml>=5.1 in ./lib/python3.12/site-packages (from huggingface_hub>=0.23->pgmpy) (6.0.3)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in ./lib/python3.12/site-packages (from huggingface_hub>=0.23->pgmpy) (0.25.1)
Requirement already satisfied: anyio in ./lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.23->pgmpy) (4.14.1)
Requirement already satisfied: httpcore==1.* in ./lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.23->pgmpy) (1.0.9)
Requirement already satisfied: h11>=0.16 in ./lib/python3.12/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.23->pgmpy) (0.16.0)
Requirement already satisfied: shellingham>=1.3.0 in ./lib/python3.12/site-packages (from typer<0.26.0,>=0.20.0->huggingface_hub>=0.23->pgmpy) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in ./lib/python3.12/site-packages (from typer<0.26.0,>=0.20.0->huggingface_hub>=0.23->pgmpy) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in ./lib/python3.12/site-packages (from typer<0.26.0,>=0.20.0->huggingface_hub>=0.23->pgmpy) (0.0.4)
Requirement already satisfied: decorator>=5.1.0 in ./lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets) (5.3.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in ./lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in ./lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets) (0.20.0)
Requirement already satisfied: matplotlib-inline>=0.1.6 in ./lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets) (0.2.2)
Requirement already satisfied: pexpect>4.6 in ./lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in ./lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets) (3.0.52)
Requirement already satisfied: psutil>=7 in ./lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets) (7.2.2)
Requirement already satisfied: pygments>=2.14.0 in ./lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets) (2.20.0)
Requirement already satisfied: stack_data>=0.6.0 in ./lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets) (0.6.3)
Requirement already satisfied: wcwidth in ./lib/python3.12/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.8.1)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in ./lib/python3.12/site-packages (from jedi>=0.18.2->ipython>=6.1.0->ipywidgets) (0.8.7)
Requirement already satisfied: namex in ./lib/python3.12/site-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in ./lib/python3.12/site-packages (from keras>=3.12.0->tensorflow) (0.19.1)
Requirement already satisfied: ptyprocess>=0.5 in ./lib/python3.12/site-packages (from pexpect>4.6->ipython>=6.1.0->ipywidgets) (0.7.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in ./lib/python3.12/site-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface_hub>=0.23->pgmpy) (4.2.0)
Requirement already satisfied: mdurl~=0.1 in ./lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface_hub>=0.23->pgmpy) (0.1.2)
Requirement already satisfied: executing>=1.2.0 in ./lib/python3.12/site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in ./lib/python3.12/site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (3.0.1)
Requirement already satisfied: pure-eval in ./lib/python3.12/site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (0.2.3)
Requirement already satisfied: patsy>=0.5.6 in ./lib/python3.12/site-packages (from statsmodels>=0.14.5->pgmpy) (1.0.2)
Downloading tensorflow-2.21.0-cp312-cp312-manylinux_2_27_x86_64.whl (572.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 572.6/572.6 MB 10.1 MB/s  0:00:49m0:00:0100:02
Downloading tf_keras-2.21.0-py3-none-any.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 16.2 MB/s  0:00:00
Installing collected packages: tensorflow, tf-keras
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [tf-keras]1/2 [tf-keras]
Successfully installed tensorflow-2.21.0 tf-keras-2.21.0
Note: you may need to restart the kernel to use updated packages.

In [9]:
# =================== dependencias del proyecto ==================== #
import os

import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
import sklearn as sk
import tf_keras as keras
from tf_keras import layers, regularizers


from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import (accuracy_score, f1_score,
                             precision_score, recall_score,
                             classification_report, confusion_matrix)
# ================================================================== #

In [10]:
# ======= chequeo de versiones ======= #
print("numpy:", np.__version__)
print("pandas:", pd.__version__)
print("TensorFlow:", tf.__version__)
print("scikit-learn:", sk.__version__)
# ==================================== #

numpy: 2.5.0
pandas: 3.0.4
TensorFlow: 2.21.0
scikit-learn: 1.9.0

In [11]:
# ======================== carga de los dataset ======================== #
base = "datasets/"

dataframes = {
    "Balanceado":    os.path.join(base, "postures_balanced_50000.csv"),
    "Desbalanceado": os.path.join(base, "postures_imbalanced_50000.csv"),
}

raw = {name: pd.read_csv(path) for name, path in dataframes.items()}

for name, df in raw.items():
    print(f"° {name}, shape: {df.shape}")

print("\nPrimeras filas (Balanceado):")
display(raw["Balanceado"].head())

print("\nPrimeras filas (Desbalanceado):")
display(raw["Desbalanceado"].head())
# ====================================================================== #

° Balanceado, shape: (50000, 23)
° Desbalanceado, shape: (50000, 23)

Primeras filas (Balanceado):

,Class,User,X0,Y0,Z0,X1,Y1,Z1,X2,Y2,...,Z3,X4,Y4,Z4,X5,Y5,Z5,X6,Y6,Z6
0,4,12,61.947275,135.407496,-20.554474,38.682137,89.049858,-8.439905,46.700389,150.469101,...,-30.455520,62.332455,81.884850,-19.691140,45.159813,17.067704,-79.308088,NaN,NaN,NaN
1,1,13,62.799492,50.736675,-68.975138,56.338217,77.474460,-64.680418,59.656012,17.462805,...,-45.737813,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,1,31.487777,85.870298,-47.904666,-10.991409,80.020112,-40.783903,12.858542,83.661513,...,-54.680505,61.226931,56.960649,-59.567917,NaN,NaN,NaN,NaN,NaN,NaN
3,2,14,68.744593,139.890999,8.297129,88.666925,75.668980,-42.573109,0.882151,121.883681,...,-6.692044,16.391990,93.505650,16.652949,73.089022,57.978044,-46.237332,21.047267,140.854416,39.985918
4,4,13,43.607745,144.183804,11.788656,61.446513,135.027272,3.987780,82.103598,74.991998,...,3.191450,58.724120,94.983372,-0.770625,65.004897,18.997488,-57.759273,77.840263,49.234491,-57.326648

Primeras filas (Desbalanceado):

,Class,User,X0,Y0,Z0,X1,Y1,Z1,X2,Y2,...,Z3,X4,Y4,Z4,X5,Y5,Z5,X6,Y6,Z6
0,3,8,27.223664,81.749158,-51.329624,105.730511,19.628531,-92.542984,58.585362,137.272136,...,-34.421747,82.600168,14.240770,-90.563749,3.731535,82.396533,-44.331580,60.300927,-6.138673,-78.992701
1,1,13,62.799492,50.736675,-68.975138,56.338217,77.474460,-64.680418,59.656012,17.462805,...,-45.737813,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,1,31.487777,85.870298,-47.904666,-10.991409,80.020112,-40.783903,12.858542,83.661513,...,-54.680505,61.226931,56.960649,-59.567917,NaN,NaN,NaN,NaN,NaN,NaN
3,1,12,69.731431,68.097701,-48.749863,-10.081609,82.377167,-35.627840,46.762607,9.792311,...,-38.051597,43.151214,78.818724,-43.225743,46.142755,49.030409,-95.980369,NaN,NaN,NaN
4,3,11,52.475086,93.050853,7.763829,49.576891,132.613513,17.422233,74.386492,17.077776,...,-50.050866,116.092302,47.785267,-48.935800,11.588880,87.100435,-27.528267,NaN,NaN,NaN

---
### Declaración de uso de herramientas generativas

Se utilizó asistencia de IA (Claude, Anthropic) con los siguientes propósitos:

- **Visualización de DataFrames:** al llamar `.head()` dos veces en la misma 
  celda, Jupyter solo renderizaba la última tabla.

  prompt: estoy printeando 2 dataset con .head() pero solo se ve el ultimo dataset pero los 2 print muestran los titulos

  solucion: display

---